Global:
  use_gpu: true
  epoch_num: 1000
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output_rec/rec/rec_svtr_tiny_ch_pre_add_ch_and_pre_datasets_new/
  save_epoch_step: 100
  eval_batch_step:
  - 0
  - 100
  cal_metric_during_train: true
  pretrained_model: ./pretrain_models/rec_svtr_tiny_none_ctc_ch_train/best_accuracy
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  save_res_path: ./output/rec/predicts_svtr_tiny_en.txt
Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.99
  epsilon: 8.0e-08
  weight_decay: 0.05
  no_weight_decay_name: norm pos_embed
  one_dim_param_no_weight_decay: true
  lr:
    name: Cosine
    learning_rate: 0.0001
    warmup_epoch: 5
Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
    name: STN_ON
    tps_inputsize:
    - 32
    - 64
    tps_outputsize:
    - 32
    - 100
    num_control_points: 20
    tps_margins:
    - 0.05
    - 0.05
    stn_activation: none
  Backbone:
    name: SVTRNet
    img_size:
    - 32
    - 100
    out_char_num: 25
    out_channels: 192
    patch_merging: Conv
    embed_dim:
    - 64
    - 128
    - 256
    depth:
    - 3
    - 6
    - 3
    num_heads:
    - 2
    - 4
    - 8
    mixer:
    - Local
    - Local
    - Local
    - Local
    - Local
    - Local
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    local_mixer:
    - - 7
      - 11
    - - 7
      - 11
    - - 7
      - 11
    last_stage: true
    prenorm: false
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead
Loss:
  name: CTCLoss
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /paddle/Seal_Image_Code/rec_datasets/
    label_file_list:
    - /paddle/Seal_Image_Code/rec_datasets/label_train.txt
    - /paddle/Seal_Image_Code/rec_datasets/label_rec_1.txt
    - /paddle/Seal_Image_Code/rec_datasets/label_rec_2.txt
    - /paddle/Seal_Image_Code/rec_datasets/label_rec_4.txt
    - /paddle/Seal_Image_Code/rec_datasets/label_rec_5.txt
    ratio_list:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    ext_op_transform_idx: 1
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - ABINetRecAug: null
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 64
        - 256
        padding: false
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    label_file_list: /paddle/Seal_Image_Code/rec_datasets/label_test.txt
    data_dir: /paddle/Seal_Image_Code/rec_datasets/
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 64
        - 256
        padding: false
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 256
    num_workers: 2
profiler_options: null
